{
 "title": "Cost by Team",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Team Spend MTD",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "azure_cost_by_team_usd{subscription_name=\"Azure subscription poc\"}",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Cost by Team",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "azure_cost_by_team_usd{subscription_name=\"Azure subscription poc\"}",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Untagged Resource Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "azure_cost_by_team_usd{team=\"untagged\", subscription_name=\"Azure subscription poc\"}",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "Highest Cost Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, azure_cost_by_service_usd{subscription_name=\"Azure subscription poc\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Daily Spend by Date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "azure_cost_daily_usd{subscription_name=\"Azure subscription poc\"}",
     "legendFormat": "{{date}}"
    }
   ]
  }
 ]
}